### ISSUE TITLE
scraper et problème installation requirement.txt

### ISSUE THREAD

**Issue by fastclub** [bousmahafaycal/facebook_growth#2]
Hello, j'ai deux problèmes pour ma part :
Déja je n'arrive pas à scraper avec scraper > j'ai le message Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again. j'ai essayé les deux autres extensions et je n'y arrive pas non plus.

ensuite j'ai un soucis avec l'installation de requirement.txt

"Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

help ! j'ai besoin de ce script :)

**Comment by bousmahafaycal** [comment]
Hello, peux-tu réssayer en ce qui concerne le scraper ?
Pour les requirements, j'ai trouvé ce lien qui peut t'aider https://community.home-assistant.io/t/cannot-uninstall-certifi-on-upgrade-attempt/55570

**Comment by fastclub** [comment]
Salut, merci pour ton retour. Tu es sur que la manipulation marche sur mac ? parce que je galère pas mal, tu as une alternative simple a scraper ?

**Comment by fastclub** [comment]
pareil pour le script instagram j'ai plusieurs fois erreur indent dans le code il faudrait revérifier celui ci pour les prochaines maj je pense

**Comment by bousmahafaycal** [comment]
Pour le script instagram c'est pas moi qui m'en occupe :) Oui la manipulation fonctionne sur mac. Je compte l'integrer a terme dans le code de ce script dès que j'ai du temps mais ça sera pas avant un moment.

**Comment by fastclub** [comment]
ok, quand je veux scraper il me met la fenêtre pop up suivante : Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again. tu sais d'ou ça peut venir ?

**Comment by bousmahafaycal** [comment]
Non du tout désolé. C'est pas moi non plus qui me suit occuper de la partie scraper. Moi j'ai fait que le script qui permet d'envoyer des messages. Si tu as des questions sur ce script, n'hésite pas :)
